blank_issues_enabled: false
contact_links:
  - name: "💬 Domande generali, Strategie e Suggerimenti"
    url: "https://github.com/SirBotolo21/Traduzione-Aniimo/discussions"
    about: "Per confrontarti con la community, fare domande sul gioco, discutere di build o strategie."
